server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:authordb
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          oidc-client:
            client-id: oidc-client
            client-secret: secret
            scope: openid,profile
            authorization-grant-type: authorization_code
            # Esta URI debe coincidir EXACTAMENTE con la del servidor
            redirect-uri: "http://localhost:8081/login/oauth2/code/oidc-client"
        provider:
          oidc-client:
            issuer-uri: http://127.0.0.1:9000